# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-11 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
